---
# Ingress 配置
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mix-ingress
  namespace: mix-web-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - path: /gin
            pathType: Prefix
            backend:
              service:
                name: gin
                port:
                  number: 8081
          - path: /nestjs
            pathType: Prefix
            backend:
              service:
                name: nestjs
                port:
                  number: 8082
          - path: /spring
            pathType: Prefix
            backend:
              service:
                name: spring
                port:
                  number: 8083
          - path: /fastapi
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 8084
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 9000
