---
# Namespace 定义
apiVersion: v1
kind: Namespace
metadata:
  name: mix-web-demo
  labels:
    name: mix-web-demo

---
# 网络策略
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mix-allow-ingress
  namespace: mix-web-demo
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: mix-web-demo
        - podSelector: {}
